language: cpp
sudo: false

env:
  global:

  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - gdb
      - valgrind

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:

    ###
    # All compilers, default boost
    ###

    # Clang 3.5
    - os: linux
      env: LLVM_VERSION=3.5.2 BOOST_VERSION=default COMPILER=clang++
      compiler: clang

    # Clang 3.6
    - os: linux
      env: LLVM_VERSION=3.6.2 BOOST_VERSION=default COMPILER=clang++
      compiler: clang

    # Clang 3.7
    - os: linux
      env: LLVM_VERSION=3.7.1 BOOST_VERSION=default COMPILER=clang++
      compiler: clang

    # Clang 3.8
    - os: linux
      env: LLVM_VERSION=3.8.0 BOOST_VERSION=default COMPILER=clang++
      compiler: clang

    ##
    # With varying boost versions
    ##

    - os: linux
      env: LLVM_VERSION=3.6.2 BOOST_VERSION=1.55.0 COMPILER=clang++
      compiler: clang

    - os: linux
      env: LLVM_VERSION=3.7.1 BOOST_VERSION=1.57.0 COMPILER=clang++
      compiler: clang

    - os: linux
      env: LLVM_VERSION=3.8.0 BOOST_VERSION=1.59.0 COMPILER=clang++
      compiler: clang

install:
  - ./install.sh

script:
  - ./test.sh
