language: cpp
sudo: false

env:
  global:

  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-4.9 # This is needed only to get a >= 4.7 version of libstdc++,
                # clang will fail to build without it
    sources:
      - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:

    ###
    # All compilers, default boost
    ###

    # clang 3.5
    - os: linux
      env: LLVM_VERSION=3.5.2 BOOST_VERSION=default
      compiler: clang

    # clang 3.6
    - os: linux
      env: LLVM_VERSION=3.6.2 BOOST_VERSION=default
      compiler: clang

    # clang 3.7
    - os: linux
      env: LLVM_VERSION=3.7.1 BOOST_VERSION=default
      compiler: clang

    # clang 3.8
    - os: linux
      env: LLVM_VERSION=3.8.0 BOOST_VERSION=default
      compiler: clang

    # gcc 4.9
    - os: linux
      env: GCC_VERSION=4.9.3 BOOST_VERSION=default
      compiler: gcc

    # gcc 5.1
    - os: linux
      env: GCC_VERSION=5.1.0 BOOST_VERSION=default
      compiler: gcc

    # gcc 5.2
    - os: linux
      env: GCC_VERSION=5.2.0 BOOST_VERSION=default
      compiler: gcc

    # gcc 5.3
    - os: linux
      env: GCC_VERSION=5.3.0 BOOST_VERSION=default
      compiler: gcc

    ##
    # With varying boost versions
    ##

    - os: linux
      env: LLVM_VERSION=3.6.2 BOOST_VERSION=1.55.0
      compiler: clang

    - os: linux
      env: LLVM_VERSION=3.7.1 BOOST_VERSION=1.57.0
      compiler: clang

    - os: linux
      env: LLVM_VERSION=3.8.0 BOOST_VERSION=1.59.0
      compiler: clang

install:
  - source ./install.sh

script:
  - echo ${CXX}
  - echo ${CXXFLAGS}
  - echo ${LDFLAGS}
  - echo ${BOOST_ROOT}

  - ./test.sh ${CXX} ${GCC_VERSION} ${LLVM_VERSION} ${BOOST_VERSION}
